### ISSUE TITLE
custom map lights support

### ISSUE THREAD

**Issue by gildas64** [sultim-t/vkquake-rt#11]
lights in custom maps doesn't lit. makes the map dark unless switched back to normal opengl renderer.

**Comment by sultim-t** [comment]
The file `/ovrd/world_custom_lights.txt` contains custom lights for each level. 
Each line has a format: `<mapname> <x> <y> <z> <hex color>`.

Commands:
* `rt_pfnwlightadd <r> <g> <b>`  - to add a light source around a camera. R/G/B should be in [0..255]

* `rt_pfnwlightremoveb <radius in meters>` - to remove light sources within a given radius around a camera, 

After any of the commands, a previous version of  `/ovrd/world_custom_lights.txt`  is saved to `/ovrd/backup/world_custom_lights*.txt`.

Other users can see the same light sources for custom maps only if they have the same `world_custom_lights.txt` file.

**Comment by gildas64** [comment]
> The file `/ovrd/world_custom_lights.txt` contains custom lights for each level. Each line has a format: `<mapname> <x> <y> <z> <hex color>`.
> 
> Commands:
> 
> * `rt_pfnwlightadd <r> <g> <b>`  - to add a light source around a camera. R/G/B should be in [0..255]
> * `rt_pfnwlightremoveb <radius in meters>` - to remove light sources within a given radius around a camera,
> 
> After any of the commands, a previous version of `/ovrd/world_custom_lights.txt` is saved to `/ovrd/backup/world_custom_lights*.txt`.
> 
> Other users can see the same light sources for custom maps only if they have the same `world_custom_lights.txt` file.

oh okay thanks. but i do hope adding custom lights without modifying a txt file in HLRTX will be possible soon if not on quake rtx. i can't imagine having to do that if my map has a ton of lights.
