### ISSUE TITLE
how do you make fog work ?

### ISSUE THREAD

**Issue by WabbitToonz** [sultim-t/vkquake-rt#12]
i try to add fog with command 
"fog 1 1 0 0"
i think the fog should show up as red ?
i can see the current values  in game text
but  i don't see no fog at all.

**Comment by sultim-t** [comment]
New cvars instead of 'fog':
* rt_volume_ambient
* rt_volume_far
* rt_volume_lassymetry 
* rt_volume_lintensity 
* rt_volume_lpitch 
* rt_volume_lyaw 
* rt_volume_scatter
