### ISSUE TITLE
Request: Document process for creating replacement textures or shaders

### ISSUE THREAD

**Issue by hemebond** [sultim-t/vkquake-rt#14]
I've yet to see a clear example in screenshots or videos, but I'm assuming it is possible to provide replacement textures with PBR information.

If so, could this process (how they should be provided to the game) please be documented somewhere?

**Comment by WabbitToonz** [comment]
for  textures  i was able to add 2  different ways  .  1  would be  by adding  .tga files in quake-rt\id1\textures .  And the  2nd  way  would be to add to make a ktx2  file and place  it in quake-rt\ovrd\mat\maps

**Comment by sultim-t** [comment]
### Creating custom textures

`ovrd/mat` folder contains new textures to use with the new lighting system. 
Each texture is compressed and wrapped into `.ktx2` format.

Assume that `AFLOOR` texture needs to be modified.

1. Setup environment:
    * Install [CompressonatorCLI](https://gpuopen.com/compressonator/) 
        * and append a path to its executable to `$PATH` environment variable (so `compressonatorcli.exe` can be called from anywhere)
    * Install Python3
    * Find `CreateKTX2.py` script in the `ovrd` folder
        * this tool is a part of [RTGL1](https://github.com/sultim-t/RayTracedGL1#textures)

1. Create files:
    * create folder `ovrd/matdev`
    * `ovrd/matdev/maps/AFLOOR.png` -- albedo map
        * alpha channel (transparency) is used, if Doom uses transparency for that texture 
    * `ovrd/matdev/maps/AFLOOR_rme.png`:
        * roughness in `R` channel
        * metallicity in `G` channel
        * emission in `B` channel, color is controlled by albedo map at the same pixel
    * `ovrd/matdev/maps/AFLOOR_n.png` -- normal map, `G` channel is ignored (it's assumed to be always 255) 
1. Run `CreateKTX2.py` script with Python3
    * it will pack textures from `ovrd/matdev` to `ovrd/mat`

1. Changes should be visible, when the game reloads textures (usually, on game re-enter) 

Some of the instructions can be found in Doom RT readme file: 
https://github.com/sultim-t/prboom-plus-rt/tree/master/prboom2#creating-custom-textures
