### ISSUE TITLE
"RG_CANT_FIND_PHYSICAL_DEVICE"

### ISSUE THREAD

**Issue by SneakyDingo** [sultim-t/vkquake-rt#16]
Installed as instructed, but it's giving a "Quake Error: RG_CANT_FIND_PHYSICAL_DEVICE. Use -condebug to write logs" message.

**Comment by SnaxxNZ** [comment]
What GPU do you have?

I get the same message but I only have a 5700XT which doesn't support ray tracing.
The log file says "Warning: Can't find physical device with ray tracing support"

**Comment by SneakyDingo** [comment]
Radeon RX Vega 56. I think I understand the issue now.

**Comment by ronikobrosly** [comment]
@SneakyDingo , could you share what solution you found? I have the same issue.

**Comment by Blitzwing1** [comment]
> Radeon RX Vega 56. I think I understand the issue now.

You need a GPU that supports Ray Tracing, AMD never added an RT emulation mode the way Nvidia did for their older architectures. There is a way that you can do it under Linux using wine to run the executable though as the open source RADV driver for AMD GPUs has RT emulation support built into it.

I used to run Quake 2 RTX on my Vega 56, it was phenomenally slow and blurry, think 20 FPS at 25% of 1080p resolution scale but it did work.
