### ISSUE TITLE
alias_alphatest.frag.c does not exist with appimage build

### ISSUE THREAD

**Issue by chowder3907** [sultim-t/vkquake-rt#18]
I am trying to get the appimage compiled using the build-appimage.sh file however I get the following error log:
https://pastebin.com/Fk5qx6y1
notably at the end I get the error
`meson.build:174:0: ERROR: File Shaders/Compiled/Release/alias_alphatest.frag.c does not exist.`
Would love to see better documentation or a solution.

This is on a fresh install of debian 11 bullseye

**Comment by chowder3907** [comment]
edit: I get this same bug when compiling normally without the appimage

**Comment by sultim-t** [comment]
Yes, I only tested on Windows and without a docker... so the only project files that were modified are for Visual Studio. 

These shaders are from original vkQuake, they were deleted and should be removed from the build process: 
https://github.com/sultim-t/vkquake-rt/blob/01194b8a1347577991296f200cdb9843d28fa1ed/meson.build#L81
