### ISSUE TITLE
Is it possible to integrate this into Steam version?

### ISSUE THREAD

**Issue by ssSssXS** [sultim-t/vkquake-rt#19]
If I wanna play in my steam version (rerelease) with achievements and this amazing RT mod, what should I do? Thank you!

**Comment by JoopNL** [comment]
Yes, just follow the instructions on the Releases page.

**Comment by ssSssXS** [comment]
I did. But it doesn't say how to play with Steam (to have an overlay, my saves etc). As a standalone game - I can play, yes

**Comment by sultim-t** [comment]
It's not quite possible, as the project is just a source-port

**Comment by ssSssXS** [comment]
not quite possible or not possible at all? I'm just not an expert on this ;D
