### ISSUE TITLE
AMD support

### ISSUE THREAD

**Issue by ShadF0x** [sultim-t/vkquake-rt#2]
vkQuake crashes when launched with the provided RayTracedGL1.dll. No error message, just "vkQuake has stopped working".

Using Serious Sam's .dll or building one from the source results in this error message:
![image](https://user-images.githubusercontent.com/38113636/193615041-aa4e575e-9bb7-4a36-9bf6-fcf97f9fc86a.png)

OS: Windows 10 21H2 (build 19044)
GPU: AMD Radeon RX 6900 XT, running 22.9.2 driver.

**Comment by patientx** [comment]
For me (rx 6600) it does show white screen than closes. No errors.

**Comment by kd-11** [comment]
I may take a look at this one on my 6700XT, though it may take a few days before I have some time to check why it doesn't work.

**Comment by sultim-t** [comment]
That would be extremely nice, thank you!

**Comment by FreiherrSeymore** [comment]
Sadly 6900HX + 3080 Ti mobile also crashes at start with no errors

**Comment by urielejh** [comment]
got a 6900xt... i start the game but it returns to desktop after a few secs of the app's white screen.

**Comment by urielejh** [comment]
> 

same here with a 6900xt

**Comment by joseywales72** [comment]
Game starts with a blank white screen, then after a few seconds, returns to the desktop. Radeon 6500XT, latest AMD drivers.

**Comment by Blitzwing1** [comment]
Ray tracing Initialization
ModLoad: 00007ff8`bf4f0000 00007ff8`bf51f000   C:\Windows\SYSTEM32\dwmapi.dll
ModLoad: 00007ff8`c1580000 00007ff8`c15ac000   C:\Windows\SYSTEM32\DEVOBJ.dll
ModLoad: 00007ff8`c1f90000 00007ff8`c1ff7000   C:\Windows\System32\WINTRUST.dll
ModLoad: 00007ff8`c1a00000 00007ff8`c1b62000   C:\Windows\System32\CRYPT32.dll
ModLoad: 00007ff8`c1120000 00007ff8`c1132000   C:\Windows\SYSTEM32\MSASN1.dll
(440c.3e44): Access violation - code c0000005 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
amdvlk64+0x62c5e:
00007ff8`215d2c5e 4a8b743318      mov     rsi,qword ptr [rbx+r14+18h] ds:00000000`00000018=????????????????
0:000> g
(440c.3e44): Access violation - code c0000005 (!!! second chance !!!)
amdvlk64+0x62c5e:
00007ff8`215d2c5e 4a8b743318      mov     rsi,qword ptr [rbx+r14+18h] ds:00000000`00000018=????????????????

Windows 11 latest AMD drivers.

It also crashes at the same place, same error when running via wine.

**Comment by Calinou** [comment]
This issue has been confirmed several times already (on different hardware configurations). There's no need to confirm it further, as it only creates useless notifications for people watching this repository :slightly_smiling_face:

**Comment by kd-11** [comment]
I've submitted the patch for this here: https://github.com/sultim-t/RayTracedGL1/pull/21
If you're technically inclined you may build it and try it for yourself, or wait for the next release by the maintainer.

**Comment by sultim-t** [comment]
https://github.com/sultim-t/vkquake-rt/releases/tag/1.20.2-rt1.0.2

Let's see if it works :)

**Comment by ShadF0x** [comment]
> https://github.com/sultim-t/vkquake-rt/releases/tag/1.20.2-rt1.0.2
> 
> Let's see if it works :)

Seems so.

![image](https://user-images.githubusercontent.com/38113636/194271212-40bd3ceb-af05-4937-a7c9-d1db8dea83c3.png)

**Comment by FreiherrSeymore** [comment]
Sadly not really on my 6900HX + 3080 TI mobile here. 

Game starts now but freezes and crashes in demo1 while hes shooting the grenade launcher. Starting new game also crashes

**Comment by kd-11** [comment]
Maybe it's running on the integrated GPU. The only issue I can think of there is memory restrictions. Try disabling the igpu or updating its drivers.

**Comment by FreiherrSeymore** [comment]
Its a brand new and freshly updated Asus Duo running newest drivers and over 50 new games ive just tested. I dont think its a problem on my machine but ill test a bit and tell you if something works. On my Intel Nvidia desktop everything runs fine.

Really hope for a solution, i love Quake so much and was already praying for RT Quake for years. Ill also have to rely just on my new laptop the next years because of my job.

**Comment by urielejh** [comment]
> https://github.com/sultim-t/vkquake-rt/releases/tag/1.20.2-rt1.0.2
> 
> Let's see if it works :)

6900xt here. it works. is there a way to put in fsr 2.1?

**Comment by sultim-t** [comment]
Oof, I just forgot to rename the menu option after integrating AMD FSR 2.1. It's there, ignore the menu text :)

**Comment by FreiherrSeymore** [comment]
Another small update regarding the issue of this release strangely just using my laptop intgrated AMD GPU: Forcing the dedicated NVIDIA GPU via driver for the exe works. its running with perfect performance now

**Comment by jonathancumming** [comment]
6900xt here, that new version works for me, Thanks! :D

**Comment by ghost** [comment]
![image](https://github.com/sultim-t/vkquake-rt/assets/5371279/6b21c0db-fdfc-4e13-8905-ea67a7010f03)
It doesn't look right on RX 7900 XTX.
