### ISSUE TITLE
Some thoughts

### ISSUE THREAD

**Issue by donizettilorenzo** [sultim-t/vkquake-rt#7]
*Vulkan runtime on not hw accelerated GPUs (1660/1660 Ti) are slower than Q2RTX one (but still working)
*FSR 2.1 is already available, please update
*there's a strange bug about textures: if I shoot - with the shotgun - a black wall ('cause of shadows) it lights up.....and remains bright until the viewport changes (rotation, etc).

**Comment by sultim-t** [comment]
* It's amazing that it works on 1660, I would  try to optimize, if I had that hardware in addition
* I just forgot to rename the button, FSR 2.1 is there
* This is a temporal lag, and temporal accumulation should be tweaked, but it's quite hard. There's a chance that the current algorithm will be replaced

**Comment by donizettilorenzo** [comment]
It works well on the 1660 Ti, but @1280x720 I got 25 FPS literally everywhere :| (Q2 RTX 40 FPS but in Q2 we got more tweaking options like the global illumination complexity and so on)

**Comment by sultim-t** [comment]
I didn't expect 25FPS. Is it without AMD FSR? There's  direct dependency between render size and performance, so AMD FSR is a must in your case :)

**Comment by donizettilorenzo** [comment]
Yes, exactly. There's why temporal upscalars are essential to raytracing via classic shaders.

**Comment by donizettilorenzo** [comment]
(ah, you're famous now, Digital Foundry -> https://youtu.be/lLCICvjJuR0?t=1156 )

**Comment by donizettilorenzo** [comment]
Full video :D https://www.youtube.com/watch?v=IhhLcZQ2zD0&ab_channel=DigitalFoundry
